# Generated by Django 4.1.2 on 2022-11-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_answers_questions_report_forms_answers_question_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerVariants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.answers"
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.questions"
                    ),
                ),
            ],
        ),
    ]
